name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # You can specify the Python version here
      - name: Install requests library
        run: pip install requests
      - name: Run Python script
        run: python .github/workflows/pythonscript1.py  # Specify the path to your Python script here
      - name: list files
        run: ls
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          username: shlomoko11
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@4a531fa5a603bab87dfa56578bd82b28508c9547
        uses: docker/build-push-action@v2.2.2
        with:
          context:  .
          file:  ./Dockerfile
          tags:  shlomoko11/products-lastversions:latest
          push:  true
